# Generated by Django 3.0.7 on 2020-07-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('head_img', models.FileField(default='', upload_to='images')),
                ('content_main', models.TextField()),
                ('slug', models.CharField(max_length=1000)),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
    ]
